/* tslint:disable */
export { AttributeMock, IAttributeComponents } from "./page/attribute/attribute.mock";
export { AutoLookupControlMock, IAttAutoLookupControlComponents, IAutoLookupControlComponents } from "./page/autolookupcontrol/autolookupcontrol.mock";
export { BooleanAttributeMock } from "./page/booleanattribute/booleanattribute.mock";
export { ClientContextMock } from "./clientcontext/clientcontext.mock";
export { ContextMock, IContextComponents } from "./context/context.mock";
export { ControlMock } from "./page/control/control.mock";
export { DataMock } from "./data/data.mock";
export { DateAttributeMock, IDateAttributeComponents } from "./page/dateattribute/dateattribute.mock";
export { DateControlMock } from "./page/datecontrol/datecontrol.mock";
export { EntityMock } from "./page/entity/entity.mock";
export { EnumAttributeMock } from "./page/enumattribute/enumattribute.mock";
export { FormItemMock, IFormItemComponents } from "./page/formitem/formitem.mock";
export { FormOpenParametersMock } from "./utility/formopenparameters/formopenparameters.mock";
export { FormSelectorMock } from "./page/formselector/formselector.mock";
export { ItemCollectionMock } from "./collection/itemcollection/itemcollection.mock";
export { LookupAttributeMock } from "./page/lookupattribute/lookupattribute.mock";
export { LookupValueMock } from "./page/lookupvalue/lookupvalue.mock";
export { NumberAttributeMock } from "./page/numberattribute/numberattribute.mock";
export { NumberControlMock } from "./page/numbercontrol/numbercontrol.mock";
export { OpenParametersMock } from "./utility/openparameters/openparameters.mock";
export { IOptionSetAttributeComponents, OptionSetAttributeMock } from "./page/optionsetattribute/optionsetattribute.mock";
export { IAttOptionSetControlComponents, IOptionSetControlComponents, OptionSetControlMock } from "./page/optionsetcontrol/optionsetcontrol.mock";
export { OptionSetValueMock } from "./page/optionsetvalue/optionsetvalue.mock";
export { PageMock, IPageComponents } from "./page/page.mock";
export { ProcessDictionaryMock } from "./data/processdictionary/processdictionary.mock";
export { ProcessManagerMock } from "./data/processmanager/processmanager.mock";
export { ProcessMock, IProcessComponents } from "./page/process/process.mock";
export { SectionMock } from "./page/section/section.mock";
export { StageMock } from "./page/stage/stage.mock";
export { IAttStandardControlComponents, IStandardControlComponents, StandardControlMock } from "./page/standardcontrol/standardcontrol.mock";
export { StepMock } from "./page/step/step.mock";
export { IStringAttributeComponents, StringAttributeMock } from "./page/stringattribute/stringattribute.mock";
export { IAttStringControlComponents, IStringControlComponents, StringControlMock } from "./page/stringcontrol/stringcontrol.mock";
export { UiCanGetVisibleElementMock } from "./page/uicangetvisibleelement/uicangetvisibleelement.mock";
export { UiFocusableMock } from "./page/uifocusable/uifocusable.mock";
export { UiKeyPressableMock } from "./page/uikeypressable/uikeypressable.mock";
export { UiLabelElementMock } from "./page/uilabelelement/uilabelelement.mock";
export { UiMock } from "./ui/ui.mock";
export { UiStandardElementMock } from "./page/uistandardelement/uistandardelement.mock";
export { UtilityMock } from "./utility/utility.mock";
export { WindowMock } from "./window.mock";
export { XrmStaticMock, IXrmStaticComponents } from "./xrmstatic.mock";
